version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.13.0

commands:
  restore_npm:
    steps:
      # Download and cache dependencies
      - restore_cache:
          name: Restore npm dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install dependencies
          command: yarn install
      - save_npm

  build_and_deploy_presenter:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: build presenter
          command: yarn build:presenter
      - run:
          name: Deploy to GAS.
          command: yarn deploy:presenter


  build_and_deploy_audience:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: build audience
          command: yarn build:audience
      - run:
          name: Deploy to GAS.
          command: yarn deploy:audience

workflows:
  version: 2
  setup_and_ci:
    jobs:
      - setup
      - build_and_deploy_presenter:
          filters:
            branches:
              only: master
          requires:
            - setup
      - build_and_deploy_audience:
          filters:
            branches:
              only: master
          requires:
            - setup
