version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.20.1

commands:
  restore_node_modules:
    steps:
      # Download and cache dependencies
      - restore_cache:
          name: Restore node_modules
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  save_node_modules:
    steps:
      - save_cache:
          name: Cache node_modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_node_modules

  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: lint
          command: yarn lint

  type_check:
    executor:
      name: default
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: type-check
          command: yarn type-check

  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: build
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - dist

  deploy:
    executor:
      name: default
    steps:
      - checkout
      - restore_node_modules
      - attach_workspace:
          at: ./
      - run:
          name: Deploy to GAS.
          command: yarn deploy

workflows:
  version: 2
  setup_and_ci:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - type_check:
          requires:
            - setup
      - build:
          requires:
            - setup
            - lint
            - type_check
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
